# Generated by Django 5.2.7 on 2025-11-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor', 'room_number']},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={},
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(default='single', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='room',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/thumbnails/'),
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='view',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
