# Generated by Django 5.2.7 on 2025-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at']},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='chapa_reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money / Chapa')], default='mobile', max_length=20),
        ),
    ]
